# =============================================
# DATABASE
# =============================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# =============================================
# JPA / HIBERNATE
# =============================================
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
spring.jpa.open-in-view=false
spring.jpa.show-sql=${SHOW_SQL:false}

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# =============================================
# FLYWAY
# =============================================
spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration


# =============================================
# SERVER
# =============================================
server.port=${PORT:8080}


# =============================================
# OPENAPI / SWAGGER
# =============================================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html


# =============================================
# DNI API
# =============================================
dni.api.base-url=${DNI_API_BASE_URL:https://api.apis.net.pe}
dni.api.token=${DNI_API_TOKEN}


# =============================================
# BREVO EMAIL
# =============================================
brevo.api.url=https://api.brevo.com
brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=${BREVO_SENDER_EMAIL}
brevo.sender.name=NeoDent


# =============================================
# JWT
# =============================================
jwt.secret=${JWT_SECRET}
jwt.expiration-minutes=15
jwt.refresh-expiration-days=7


# =============================================
# TURNSTILE
# =============================================
turnstile.secret=${TURNSTILE_SECRET}
turnstile.verify-url=https://challenges.cloudflare.com/turnstile/v0/siteverify


# =============================================
# FRONTEND
# =============================================
app.frontend-url=${FRONTEND_URL:http://localhost:5173}